# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];


  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/1f398a63-ca94-4db6-8456-37c25b2f510f";
      fsType = "ext4";
    };
    "/mnt/data1" = {
      device = "/dev/disk/by-label/data1";
      fsType = "btrfs";
      options = [ "defaults" "noatime" "compress=zstd" ];
      neededForBoot = false;
    };
    "/mnt/data2" = {
      device = "/dev/disk/by-label/data2";
      fsType = "btrfs";
      options = [ "defaults" "noatime" "compress=zstd" ];
      neededForBoot = false;
    };
  };


  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."luks-361c8378-276e-4a51-92a0-860a425849f6".device = "/dev/disk/by-uuid/361c8378-276e-4a51-92a0-860a425849f6";
  boot.initrd.luks.devices."luks-1b80c475-24c3-4d16-95a7-63bde902afca".device = "/dev/disk/by-uuid/1b80c475-24c3-4d16-95a7-63bde902afca";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/53F3-FCF2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/1475142e-bc04-4751-a9a1-e5220dda3a01"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
